### ISSUE TITLE
bandwidth need parse to int 

### ISSUE THREAD

**Issue by bingo235** [pion/ion-sdk-flutter#11]
https://github.com/pion/ion-sdk-flutter/blob/f5ad9234facaed0c83a33b6c48624be0a513caee/lib/src/client.dart#L129-L135

PublishOptions in ion defined as int

https://github.com/pion/ion/blob/843f94f1a00518ce3ac27661b952ba52904aa395/pkg/proto/biz.go#L22-L29

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/pion/ion-sdk-flutter/commit/a794a875eff9c7db7f2876faf5315a6e8e646b23
