### ISSUE TITLE
How do we know remote stream which has been removed

### ISSUE THREAD

**Issue by Barry0501** [pion/ion-sdk-flutter#26]
Hi author, I notice in flutter-webrtc's example they have a method onRemoveRemoteStream to know remote stream has been removed. But I try found the same method in your lib, it doesn't exist. Please help me if I miss something.
<img width="524" alt="Screen Shot 2020-12-01 at 14 21 32" src="https://user-images.githubusercontent.com/34902237/100709354-857a2e80-33e0-11eb-86f1-2a0851cfee7a.png">

**Comment by jpcodr** [comment]
Hi @Barry0501

Did you found any solution to this?
