### ISSUE TITLE
Support for null safety

### ISSUE THREAD

**Issue by gargakshit** [pion/ion-sdk-flutter#34]
Flutter 2.0 is out with support for null safety in the stable branch. It would be really nice if ion-sdk-flutter supported sound null safety

**Comment by cloudwebrtc** [comment]
Depend on solving this issue first https://github.com/flutter-webrtc/flutter-webrtc/issues/458

**Comment by cloudwebrtc** [comment]
https://pub.dev/packages/flutter_ion
Support now.
