### ISSUE TITLE
onPeerEvent not triggered upon joining a room

### ISSUE THREAD

**Issue by Ayush412** [pion/ion-sdk-flutter#62]
### Your environment.
  - Flutter:  2.8.1
  - SDK Release: v1.0.0
  - Device: iOS and Android

### What did you do?

Tested the [ion-app-flutter](https://github.com/pion/ion-app-flutter) with our own server. No modifications made to backend code. Audio and video work fine.

### What did you expect?

Expected `onPeerEvent` to trigger for all users (those already in the room AND those who just joined) to retrieve Peer object for displaying user information.

### What happened?

`onPeerEvent` is only triggered for users who are already in the room, not for the user joining. Once this user is in the room, `onPeerEvent` is triggered for every new user thereafter. **_This was not the behavior in previous releases_** (i.e. v0.5.4 and below)

If this is how it should behave, what method/listener should I rely on to get Peer information of existing users upon joining?

Side question - How can users update their Peer information (name, extrainfo, role, etc) and send the update to every user in the room?

**Comment by ctapp1** [comment]
I am curious about this as well.

**Comment by Ayush412** [comment]
Updating backend to [master](https://github.com/pion/ion) branch fixed the issue. Looks like it was fixed in [this commit](https://github.com/pion/ion/commit/6fc0e09e275e72383f3de8a346fb56e0e063d5b1).
